all:
	pdflatex AntiFuzzing1.tex
	bibtex AntiFuzzing1
	pdflatex AntiFuzzing1.tex
	pdflatex AntiFuzzing1.tex
	open AntiFuzzing1.pdf
clean:
	rm -f *.aux
	rm -f *.idx
	rm -f *.out
	rm -f *.log
	rm -f *.dvi
	rm -f *.blg
	rm -f *.bbl
	rm -f *.pdf
	rm -f *.ps
